export const REPORTING_REPOSITORY_TOKEN = 'REPORTING_REPOSITORY_TOKEN';

export enum DashboardRole {
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  PARENT = 'PARENT',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  ORGANIZATION_ADMIN = 'ORGANIZATION_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum ReportType {
  STUDENT_PROGRESS = 'STUDENT_PROGRESS',
  ATTENDANCE = 'ATTENDANCE',
  ASSESSMENT = 'ASSESSMENT',
  ASSIGNMENT = 'ASSIGNMENT',
  LEARNING_DNA = 'LEARNING_DNA',
  VEDHKRIT_INDEX = 'VEDHKRIT_INDEX',
  CAREER_READINESS = 'CAREER_READINESS',
  TEACHER_PERFORMANCE = 'TEACHER_PERFORMANCE',
  SCHOOL_PERFORMANCE = 'SCHOOL_PERFORMANCE',
  ORGANIZATION_PERFORMANCE = 'ORGANIZATION_PERFORMANCE',
  CUSTOM = 'CUSTOM',
}

export enum ExportFormat {
  PDF = 'PDF',
  EXCEL = 'EXCEL',
  CSV = 'CSV',
  JSON = 'JSON',
}

export enum ExportStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ScheduleFrequency {
  ONE_TIME = 'ONE_TIME',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}
