/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MentoringProgramRouteImport } from './routes/mentoring-program'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as DashboardSuperRouteImport } from './routes/dashboard.super'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardParentRouteImport } from './routes/dashboard.parent'
import { Route as DashboardMentorRouteImport } from './routes/dashboard.mentor'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as MarketingStoriesRouteImport } from './routes/_marketing.stories'
import { Route as MarketingSlecRouteImport } from './routes/_marketing.slec'
import { Route as MarketingMentoringRouteImport } from './routes/_marketing.mentoring'
import { Route as MarketingFrameworkRouteImport } from './routes/_marketing.framework'
import { Route as MarketingDemoRouteImport } from './routes/_marketing.demo'
import { Route as MarketingContactRouteImport } from './routes/_marketing.contact'
import { Route as MarketingCareerRouteImport } from './routes/_marketing.career'
import { Route as MarketingAssessmentRouteImport } from './routes/_marketing.assessment'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as DashboardSuperIndexRouteImport } from './routes/dashboard.super.index'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard.student.index'
import { Route as DashboardParentIndexRouteImport } from './routes/dashboard.parent.index'
import { Route as DashboardMentorIndexRouteImport } from './routes/dashboard.mentor.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardSuperUsersRouteImport } from './routes/dashboard.super.users'
import { Route as DashboardSuperSubscriptionsRouteImport } from './routes/dashboard.super.subscriptions'
import { Route as DashboardSuperSchoolsRouteImport } from './routes/dashboard.super.schools'
import { Route as DashboardSuperRevenueRouteImport } from './routes/dashboard.super.revenue'
import { Route as DashboardSuperActivityRouteImport } from './routes/dashboard.super.activity'
import { Route as DashboardStudentSkillsRouteImport } from './routes/dashboard.student.skills'
import { Route as DashboardStudentSessionsRouteImport } from './routes/dashboard.student.sessions'
import { Route as DashboardStudentReportsRouteImport } from './routes/dashboard.student.reports'
import { Route as DashboardStudentProfileRouteImport } from './routes/dashboard.student.profile'
import { Route as DashboardStudentPortfolioRouteImport } from './routes/dashboard.student.portfolio'
import { Route as DashboardStudentPlannerRouteImport } from './routes/dashboard.student.planner'
import { Route as DashboardStudentMentorRouteImport } from './routes/dashboard.student.mentor'
import { Route as DashboardStudentGoalsRouteImport } from './routes/dashboard.student.goals'
import { Route as DashboardStudentCareerRouteImport } from './routes/dashboard.student.career'
import { Route as DashboardStudentAssessmentsRouteImport } from './routes/dashboard.student.assessments'
import { Route as DashboardStudentAiRouteImport } from './routes/dashboard.student.ai'
import { Route as DashboardStudentAcademicsRouteImport } from './routes/dashboard.student.academics'
import { Route as DashboardParentReportsRouteImport } from './routes/dashboard.parent.reports'
import { Route as DashboardParentRecommendationsRouteImport } from './routes/dashboard.parent.recommendations'
import { Route as DashboardParentMentorNotesRouteImport } from './routes/dashboard.parent.mentor-notes'
import { Route as DashboardParentGrowthRouteImport } from './routes/dashboard.parent.growth'
import { Route as DashboardParentCommunicationRouteImport } from './routes/dashboard.parent.communication'
import { Route as DashboardParentAttendanceRouteImport } from './routes/dashboard.parent.attendance'
import { Route as DashboardMentorStudentsRouteImport } from './routes/dashboard.mentor.students'
import { Route as DashboardMentorSessionsRouteImport } from './routes/dashboard.mentor.sessions'
import { Route as DashboardMentorProgressRouteImport } from './routes/dashboard.mentor.progress'
import { Route as DashboardMentorPlansRouteImport } from './routes/dashboard.mentor.plans'
import { Route as DashboardMentorAlertsRouteImport } from './routes/dashboard.mentor.alerts'
import { Route as DashboardAdminTeachersRouteImport } from './routes/dashboard.admin.teachers'
import { Route as DashboardAdminStudentsRouteImport } from './routes/dashboard.admin.students'
import { Route as DashboardAdminReportsRouteImport } from './routes/dashboard.admin.reports'
import { Route as DashboardAdminProfileRouteImport } from './routes/dashboard.admin.profile'
import { Route as DashboardAdminMentorsRouteImport } from './routes/dashboard.admin.mentors'
import { Route as DashboardAdminMembershipRouteImport } from './routes/dashboard.admin.membership'
import { Route as DashboardAdminCmsRouteImport } from './routes/dashboard.admin.cms'
import { Route as DashboardAdminAnalyticsRouteImport } from './routes/dashboard.admin.analytics'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoringProgramRoute = MentoringProgramRouteImport.update({
  id: '/mentoring-program',
  path: '/mentoring-program',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DashboardSuperRoute = DashboardSuperRouteImport.update({
  id: '/dashboard/super',
  path: '/dashboard/super',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardParentRoute = DashboardParentRouteImport.update({
  id: '/dashboard/parent',
  path: '/dashboard/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMentorRoute = DashboardMentorRouteImport.update({
  id: '/dashboard/mentor',
  path: '/dashboard/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingStoriesRoute = MarketingStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSlecRoute = MarketingSlecRouteImport.update({
  id: '/slec',
  path: '/slec',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingMentoringRoute = MarketingMentoringRouteImport.update({
  id: '/mentoring',
  path: '/mentoring',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFrameworkRoute = MarketingFrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDemoRoute = MarketingDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCareerRoute = MarketingCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAssessmentRoute = MarketingAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const DashboardSuperIndexRoute = DashboardSuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSuperRoute,
} as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardParentIndexRoute = DashboardParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardParentRoute,
} as any)
const DashboardMentorIndexRoute = DashboardMentorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMentorRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardSuperUsersRoute = DashboardSuperUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardSuperRoute,
} as any)
const DashboardSuperSubscriptionsRoute =
  DashboardSuperSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => DashboardSuperRoute,
  } as any)
const DashboardSuperSchoolsRoute = DashboardSuperSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => DashboardSuperRoute,
} as any)
const DashboardSuperRevenueRoute = DashboardSuperRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => DashboardSuperRoute,
} as any)
const DashboardSuperActivityRoute = DashboardSuperActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardSuperRoute,
} as any)
const DashboardStudentSkillsRoute = DashboardStudentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentSessionsRoute =
  DashboardStudentSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentReportsRoute = DashboardStudentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentProfileRoute = DashboardStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentPortfolioRoute =
  DashboardStudentPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentPlannerRoute = DashboardStudentPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentMentorRoute = DashboardStudentMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentGoalsRoute = DashboardStudentGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentCareerRoute = DashboardStudentCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentAssessmentsRoute =
  DashboardStudentAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentAiRoute = DashboardStudentAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentAcademicsRoute =
  DashboardStudentAcademicsRouteImport.update({
    id: '/academics',
    path: '/academics',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardParentReportsRoute = DashboardParentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardParentRoute,
} as any)
const DashboardParentRecommendationsRoute =
  DashboardParentRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => DashboardParentRoute,
  } as any)
const DashboardParentMentorNotesRoute =
  DashboardParentMentorNotesRouteImport.update({
    id: '/mentor-notes',
    path: '/mentor-notes',
    getParentRoute: () => DashboardParentRoute,
  } as any)
const DashboardParentGrowthRoute = DashboardParentGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => DashboardParentRoute,
} as any)
const DashboardParentCommunicationRoute =
  DashboardParentCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => DashboardParentRoute,
  } as any)
const DashboardParentAttendanceRoute =
  DashboardParentAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardParentRoute,
  } as any)
const DashboardMentorStudentsRoute = DashboardMentorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardMentorRoute,
} as any)
const DashboardMentorSessionsRoute = DashboardMentorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardMentorRoute,
} as any)
const DashboardMentorProgressRoute = DashboardMentorProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardMentorRoute,
} as any)
const DashboardMentorPlansRoute = DashboardMentorPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardMentorRoute,
} as any)
const DashboardMentorAlertsRoute = DashboardMentorAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardMentorRoute,
} as any)
const DashboardAdminTeachersRoute = DashboardAdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminStudentsRoute = DashboardAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminReportsRoute = DashboardAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminProfileRoute = DashboardAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminMentorsRoute = DashboardAdminMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminMembershipRoute =
  DashboardAdminMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminCmsRoute = DashboardAdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAnalyticsRoute = DashboardAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/assessments': typeof AssessmentsRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/mentoring-program': typeof MentoringProgramRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/about': typeof MarketingAboutRoute
  '/assessment': typeof MarketingAssessmentRoute
  '/career': typeof MarketingCareerRoute
  '/contact': typeof MarketingContactRoute
  '/demo': typeof MarketingDemoRoute
  '/framework': typeof MarketingFrameworkRoute
  '/mentoring': typeof MarketingMentoringRoute
  '/slec': typeof MarketingSlecRoute
  '/stories': typeof MarketingStoriesRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/mentor': typeof DashboardMentorRouteWithChildren
  '/dashboard/parent': typeof DashboardParentRouteWithChildren
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/super': typeof DashboardSuperRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/cms': typeof DashboardAdminCmsRoute
  '/dashboard/admin/membership': typeof DashboardAdminMembershipRoute
  '/dashboard/admin/mentors': typeof DashboardAdminMentorsRoute
  '/dashboard/admin/profile': typeof DashboardAdminProfileRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/mentor/alerts': typeof DashboardMentorAlertsRoute
  '/dashboard/mentor/plans': typeof DashboardMentorPlansRoute
  '/dashboard/mentor/progress': typeof DashboardMentorProgressRoute
  '/dashboard/mentor/sessions': typeof DashboardMentorSessionsRoute
  '/dashboard/mentor/students': typeof DashboardMentorStudentsRoute
  '/dashboard/parent/attendance': typeof DashboardParentAttendanceRoute
  '/dashboard/parent/communication': typeof DashboardParentCommunicationRoute
  '/dashboard/parent/growth': typeof DashboardParentGrowthRoute
  '/dashboard/parent/mentor-notes': typeof DashboardParentMentorNotesRoute
  '/dashboard/parent/recommendations': typeof DashboardParentRecommendationsRoute
  '/dashboard/parent/reports': typeof DashboardParentReportsRoute
  '/dashboard/student/academics': typeof DashboardStudentAcademicsRoute
  '/dashboard/student/ai': typeof DashboardStudentAiRoute
  '/dashboard/student/assessments': typeof DashboardStudentAssessmentsRoute
  '/dashboard/student/career': typeof DashboardStudentCareerRoute
  '/dashboard/student/goals': typeof DashboardStudentGoalsRoute
  '/dashboard/student/mentor': typeof DashboardStudentMentorRoute
  '/dashboard/student/planner': typeof DashboardStudentPlannerRoute
  '/dashboard/student/portfolio': typeof DashboardStudentPortfolioRoute
  '/dashboard/student/profile': typeof DashboardStudentProfileRoute
  '/dashboard/student/reports': typeof DashboardStudentReportsRoute
  '/dashboard/student/sessions': typeof DashboardStudentSessionsRoute
  '/dashboard/student/skills': typeof DashboardStudentSkillsRoute
  '/dashboard/super/activity': typeof DashboardSuperActivityRoute
  '/dashboard/super/revenue': typeof DashboardSuperRevenueRoute
  '/dashboard/super/schools': typeof DashboardSuperSchoolsRoute
  '/dashboard/super/subscriptions': typeof DashboardSuperSubscriptionsRoute
  '/dashboard/super/users': typeof DashboardSuperUsersRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/mentor/': typeof DashboardMentorIndexRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/super/': typeof DashboardSuperIndexRoute
}
export interface FileRoutesByTo {
  '/assessments': typeof AssessmentsRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/mentoring-program': typeof MentoringProgramRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/about': typeof MarketingAboutRoute
  '/assessment': typeof MarketingAssessmentRoute
  '/career': typeof MarketingCareerRoute
  '/contact': typeof MarketingContactRoute
  '/demo': typeof MarketingDemoRoute
  '/framework': typeof MarketingFrameworkRoute
  '/mentoring': typeof MarketingMentoringRoute
  '/slec': typeof MarketingSlecRoute
  '/stories': typeof MarketingStoriesRoute
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/cms': typeof DashboardAdminCmsRoute
  '/dashboard/admin/membership': typeof DashboardAdminMembershipRoute
  '/dashboard/admin/mentors': typeof DashboardAdminMentorsRoute
  '/dashboard/admin/profile': typeof DashboardAdminProfileRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/mentor/alerts': typeof DashboardMentorAlertsRoute
  '/dashboard/mentor/plans': typeof DashboardMentorPlansRoute
  '/dashboard/mentor/progress': typeof DashboardMentorProgressRoute
  '/dashboard/mentor/sessions': typeof DashboardMentorSessionsRoute
  '/dashboard/mentor/students': typeof DashboardMentorStudentsRoute
  '/dashboard/parent/attendance': typeof DashboardParentAttendanceRoute
  '/dashboard/parent/communication': typeof DashboardParentCommunicationRoute
  '/dashboard/parent/growth': typeof DashboardParentGrowthRoute
  '/dashboard/parent/mentor-notes': typeof DashboardParentMentorNotesRoute
  '/dashboard/parent/recommendations': typeof DashboardParentRecommendationsRoute
  '/dashboard/parent/reports': typeof DashboardParentReportsRoute
  '/dashboard/student/academics': typeof DashboardStudentAcademicsRoute
  '/dashboard/student/ai': typeof DashboardStudentAiRoute
  '/dashboard/student/assessments': typeof DashboardStudentAssessmentsRoute
  '/dashboard/student/career': typeof DashboardStudentCareerRoute
  '/dashboard/student/goals': typeof DashboardStudentGoalsRoute
  '/dashboard/student/mentor': typeof DashboardStudentMentorRoute
  '/dashboard/student/planner': typeof DashboardStudentPlannerRoute
  '/dashboard/student/portfolio': typeof DashboardStudentPortfolioRoute
  '/dashboard/student/profile': typeof DashboardStudentProfileRoute
  '/dashboard/student/reports': typeof DashboardStudentReportsRoute
  '/dashboard/student/sessions': typeof DashboardStudentSessionsRoute
  '/dashboard/student/skills': typeof DashboardStudentSkillsRoute
  '/dashboard/super/activity': typeof DashboardSuperActivityRoute
  '/dashboard/super/revenue': typeof DashboardSuperRevenueRoute
  '/dashboard/super/schools': typeof DashboardSuperSchoolsRoute
  '/dashboard/super/subscriptions': typeof DashboardSuperSubscriptionsRoute
  '/dashboard/super/users': typeof DashboardSuperUsersRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/mentor': typeof DashboardMentorIndexRoute
  '/dashboard/parent': typeof DashboardParentIndexRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
  '/dashboard/super': typeof DashboardSuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/assessments': typeof AssessmentsRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/mentoring-program': typeof MentoringProgramRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/assessment': typeof MarketingAssessmentRoute
  '/_marketing/career': typeof MarketingCareerRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/demo': typeof MarketingDemoRoute
  '/_marketing/framework': typeof MarketingFrameworkRoute
  '/_marketing/mentoring': typeof MarketingMentoringRoute
  '/_marketing/slec': typeof MarketingSlecRoute
  '/_marketing/stories': typeof MarketingStoriesRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/mentor': typeof DashboardMentorRouteWithChildren
  '/dashboard/parent': typeof DashboardParentRouteWithChildren
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/super': typeof DashboardSuperRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/cms': typeof DashboardAdminCmsRoute
  '/dashboard/admin/membership': typeof DashboardAdminMembershipRoute
  '/dashboard/admin/mentors': typeof DashboardAdminMentorsRoute
  '/dashboard/admin/profile': typeof DashboardAdminProfileRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/mentor/alerts': typeof DashboardMentorAlertsRoute
  '/dashboard/mentor/plans': typeof DashboardMentorPlansRoute
  '/dashboard/mentor/progress': typeof DashboardMentorProgressRoute
  '/dashboard/mentor/sessions': typeof DashboardMentorSessionsRoute
  '/dashboard/mentor/students': typeof DashboardMentorStudentsRoute
  '/dashboard/parent/attendance': typeof DashboardParentAttendanceRoute
  '/dashboard/parent/communication': typeof DashboardParentCommunicationRoute
  '/dashboard/parent/growth': typeof DashboardParentGrowthRoute
  '/dashboard/parent/mentor-notes': typeof DashboardParentMentorNotesRoute
  '/dashboard/parent/recommendations': typeof DashboardParentRecommendationsRoute
  '/dashboard/parent/reports': typeof DashboardParentReportsRoute
  '/dashboard/student/academics': typeof DashboardStudentAcademicsRoute
  '/dashboard/student/ai': typeof DashboardStudentAiRoute
  '/dashboard/student/assessments': typeof DashboardStudentAssessmentsRoute
  '/dashboard/student/career': typeof DashboardStudentCareerRoute
  '/dashboard/student/goals': typeof DashboardStudentGoalsRoute
  '/dashboard/student/mentor': typeof DashboardStudentMentorRoute
  '/dashboard/student/planner': typeof DashboardStudentPlannerRoute
  '/dashboard/student/portfolio': typeof DashboardStudentPortfolioRoute
  '/dashboard/student/profile': typeof DashboardStudentProfileRoute
  '/dashboard/student/reports': typeof DashboardStudentReportsRoute
  '/dashboard/student/sessions': typeof DashboardStudentSessionsRoute
  '/dashboard/student/skills': typeof DashboardStudentSkillsRoute
  '/dashboard/super/activity': typeof DashboardSuperActivityRoute
  '/dashboard/super/revenue': typeof DashboardSuperRevenueRoute
  '/dashboard/super/schools': typeof DashboardSuperSchoolsRoute
  '/dashboard/super/subscriptions': typeof DashboardSuperSubscriptionsRoute
  '/dashboard/super/users': typeof DashboardSuperUsersRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/mentor/': typeof DashboardMentorIndexRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/super/': typeof DashboardSuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/forgot'
    | '/login'
    | '/mentoring-program'
    | '/register'
    | '/verify-otp'
    | '/about'
    | '/assessment'
    | '/career'
    | '/contact'
    | '/demo'
    | '/framework'
    | '/mentoring'
    | '/slec'
    | '/stories'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/parent'
    | '/dashboard/student'
    | '/dashboard/super'
    | '/dashboard/'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/cms'
    | '/dashboard/admin/membership'
    | '/dashboard/admin/mentors'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/mentor/alerts'
    | '/dashboard/mentor/plans'
    | '/dashboard/mentor/progress'
    | '/dashboard/mentor/sessions'
    | '/dashboard/mentor/students'
    | '/dashboard/parent/attendance'
    | '/dashboard/parent/communication'
    | '/dashboard/parent/growth'
    | '/dashboard/parent/mentor-notes'
    | '/dashboard/parent/recommendations'
    | '/dashboard/parent/reports'
    | '/dashboard/student/academics'
    | '/dashboard/student/ai'
    | '/dashboard/student/assessments'
    | '/dashboard/student/career'
    | '/dashboard/student/goals'
    | '/dashboard/student/mentor'
    | '/dashboard/student/planner'
    | '/dashboard/student/portfolio'
    | '/dashboard/student/profile'
    | '/dashboard/student/reports'
    | '/dashboard/student/sessions'
    | '/dashboard/student/skills'
    | '/dashboard/super/activity'
    | '/dashboard/super/revenue'
    | '/dashboard/super/schools'
    | '/dashboard/super/subscriptions'
    | '/dashboard/super/users'
    | '/dashboard/admin/'
    | '/dashboard/mentor/'
    | '/dashboard/parent/'
    | '/dashboard/student/'
    | '/dashboard/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assessments'
    | '/forgot'
    | '/login'
    | '/mentoring-program'
    | '/register'
    | '/verify-otp'
    | '/about'
    | '/assessment'
    | '/career'
    | '/contact'
    | '/demo'
    | '/framework'
    | '/mentoring'
    | '/slec'
    | '/stories'
    | '/'
    | '/dashboard'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/cms'
    | '/dashboard/admin/membership'
    | '/dashboard/admin/mentors'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/mentor/alerts'
    | '/dashboard/mentor/plans'
    | '/dashboard/mentor/progress'
    | '/dashboard/mentor/sessions'
    | '/dashboard/mentor/students'
    | '/dashboard/parent/attendance'
    | '/dashboard/parent/communication'
    | '/dashboard/parent/growth'
    | '/dashboard/parent/mentor-notes'
    | '/dashboard/parent/recommendations'
    | '/dashboard/parent/reports'
    | '/dashboard/student/academics'
    | '/dashboard/student/ai'
    | '/dashboard/student/assessments'
    | '/dashboard/student/career'
    | '/dashboard/student/goals'
    | '/dashboard/student/mentor'
    | '/dashboard/student/planner'
    | '/dashboard/student/portfolio'
    | '/dashboard/student/profile'
    | '/dashboard/student/reports'
    | '/dashboard/student/sessions'
    | '/dashboard/student/skills'
    | '/dashboard/super/activity'
    | '/dashboard/super/revenue'
    | '/dashboard/super/schools'
    | '/dashboard/super/subscriptions'
    | '/dashboard/super/users'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/parent'
    | '/dashboard/student'
    | '/dashboard/super'
  id:
    | '__root__'
    | '/_marketing'
    | '/assessments'
    | '/forgot'
    | '/login'
    | '/mentoring-program'
    | '/register'
    | '/verify-otp'
    | '/_marketing/about'
    | '/_marketing/assessment'
    | '/_marketing/career'
    | '/_marketing/contact'
    | '/_marketing/demo'
    | '/_marketing/framework'
    | '/_marketing/mentoring'
    | '/_marketing/slec'
    | '/_marketing/stories'
    | '/dashboard/admin'
    | '/dashboard/mentor'
    | '/dashboard/parent'
    | '/dashboard/student'
    | '/dashboard/super'
    | '/_marketing/'
    | '/dashboard/'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/cms'
    | '/dashboard/admin/membership'
    | '/dashboard/admin/mentors'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/mentor/alerts'
    | '/dashboard/mentor/plans'
    | '/dashboard/mentor/progress'
    | '/dashboard/mentor/sessions'
    | '/dashboard/mentor/students'
    | '/dashboard/parent/attendance'
    | '/dashboard/parent/communication'
    | '/dashboard/parent/growth'
    | '/dashboard/parent/mentor-notes'
    | '/dashboard/parent/recommendations'
    | '/dashboard/parent/reports'
    | '/dashboard/student/academics'
    | '/dashboard/student/ai'
    | '/dashboard/student/assessments'
    | '/dashboard/student/career'
    | '/dashboard/student/goals'
    | '/dashboard/student/mentor'
    | '/dashboard/student/planner'
    | '/dashboard/student/portfolio'
    | '/dashboard/student/profile'
    | '/dashboard/student/reports'
    | '/dashboard/student/sessions'
    | '/dashboard/student/skills'
    | '/dashboard/super/activity'
    | '/dashboard/super/revenue'
    | '/dashboard/super/schools'
    | '/dashboard/super/subscriptions'
    | '/dashboard/super/users'
    | '/dashboard/admin/'
    | '/dashboard/mentor/'
    | '/dashboard/parent/'
    | '/dashboard/student/'
    | '/dashboard/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AssessmentsRoute: typeof AssessmentsRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  MentoringProgramRoute: typeof MentoringProgramRoute
  RegisterRoute: typeof RegisterRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardMentorRoute: typeof DashboardMentorRouteWithChildren
  DashboardParentRoute: typeof DashboardParentRouteWithChildren
  DashboardStudentRoute: typeof DashboardStudentRouteWithChildren
  DashboardSuperRoute: typeof DashboardSuperRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoring-program': {
      id: '/mentoring-program'
      path: '/mentoring-program'
      fullPath: '/mentoring-program'
      preLoaderRoute: typeof MentoringProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/dashboard/super': {
      id: '/dashboard/super'
      path: '/dashboard/super'
      fullPath: '/dashboard/super'
      preLoaderRoute: typeof DashboardSuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/parent': {
      id: '/dashboard/parent'
      path: '/dashboard/parent'
      fullPath: '/dashboard/parent'
      preLoaderRoute: typeof DashboardParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mentor': {
      id: '/dashboard/mentor'
      path: '/dashboard/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof DashboardMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/stories': {
      id: '/_marketing/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof MarketingStoriesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/slec': {
      id: '/_marketing/slec'
      path: '/slec'
      fullPath: '/slec'
      preLoaderRoute: typeof MarketingSlecRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/mentoring': {
      id: '/_marketing/mentoring'
      path: '/mentoring'
      fullPath: '/mentoring'
      preLoaderRoute: typeof MarketingMentoringRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/framework': {
      id: '/_marketing/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof MarketingFrameworkRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/demo': {
      id: '/_marketing/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof MarketingDemoRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/career': {
      id: '/_marketing/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof MarketingCareerRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/assessment': {
      id: '/_marketing/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof MarketingAssessmentRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/dashboard/super/': {
      id: '/dashboard/super/'
      path: '/'
      fullPath: '/dashboard/super/'
      preLoaderRoute: typeof DashboardSuperIndexRouteImport
      parentRoute: typeof DashboardSuperRoute
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/parent/': {
      id: '/dashboard/parent/'
      path: '/'
      fullPath: '/dashboard/parent/'
      preLoaderRoute: typeof DashboardParentIndexRouteImport
      parentRoute: typeof DashboardParentRoute
    }
    '/dashboard/mentor/': {
      id: '/dashboard/mentor/'
      path: '/'
      fullPath: '/dashboard/mentor/'
      preLoaderRoute: typeof DashboardMentorIndexRouteImport
      parentRoute: typeof DashboardMentorRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/super/users': {
      id: '/dashboard/super/users'
      path: '/users'
      fullPath: '/dashboard/super/users'
      preLoaderRoute: typeof DashboardSuperUsersRouteImport
      parentRoute: typeof DashboardSuperRoute
    }
    '/dashboard/super/subscriptions': {
      id: '/dashboard/super/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/super/subscriptions'
      preLoaderRoute: typeof DashboardSuperSubscriptionsRouteImport
      parentRoute: typeof DashboardSuperRoute
    }
    '/dashboard/super/schools': {
      id: '/dashboard/super/schools'
      path: '/schools'
      fullPath: '/dashboard/super/schools'
      preLoaderRoute: typeof DashboardSuperSchoolsRouteImport
      parentRoute: typeof DashboardSuperRoute
    }
    '/dashboard/super/revenue': {
      id: '/dashboard/super/revenue'
      path: '/revenue'
      fullPath: '/dashboard/super/revenue'
      preLoaderRoute: typeof DashboardSuperRevenueRouteImport
      parentRoute: typeof DashboardSuperRoute
    }
    '/dashboard/super/activity': {
      id: '/dashboard/super/activity'
      path: '/activity'
      fullPath: '/dashboard/super/activity'
      preLoaderRoute: typeof DashboardSuperActivityRouteImport
      parentRoute: typeof DashboardSuperRoute
    }
    '/dashboard/student/skills': {
      id: '/dashboard/student/skills'
      path: '/skills'
      fullPath: '/dashboard/student/skills'
      preLoaderRoute: typeof DashboardStudentSkillsRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/sessions': {
      id: '/dashboard/student/sessions'
      path: '/sessions'
      fullPath: '/dashboard/student/sessions'
      preLoaderRoute: typeof DashboardStudentSessionsRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/reports': {
      id: '/dashboard/student/reports'
      path: '/reports'
      fullPath: '/dashboard/student/reports'
      preLoaderRoute: typeof DashboardStudentReportsRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/profile': {
      id: '/dashboard/student/profile'
      path: '/profile'
      fullPath: '/dashboard/student/profile'
      preLoaderRoute: typeof DashboardStudentProfileRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/portfolio': {
      id: '/dashboard/student/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/student/portfolio'
      preLoaderRoute: typeof DashboardStudentPortfolioRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/planner': {
      id: '/dashboard/student/planner'
      path: '/planner'
      fullPath: '/dashboard/student/planner'
      preLoaderRoute: typeof DashboardStudentPlannerRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/mentor': {
      id: '/dashboard/student/mentor'
      path: '/mentor'
      fullPath: '/dashboard/student/mentor'
      preLoaderRoute: typeof DashboardStudentMentorRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/goals': {
      id: '/dashboard/student/goals'
      path: '/goals'
      fullPath: '/dashboard/student/goals'
      preLoaderRoute: typeof DashboardStudentGoalsRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/career': {
      id: '/dashboard/student/career'
      path: '/career'
      fullPath: '/dashboard/student/career'
      preLoaderRoute: typeof DashboardStudentCareerRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/assessments': {
      id: '/dashboard/student/assessments'
      path: '/assessments'
      fullPath: '/dashboard/student/assessments'
      preLoaderRoute: typeof DashboardStudentAssessmentsRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/ai': {
      id: '/dashboard/student/ai'
      path: '/ai'
      fullPath: '/dashboard/student/ai'
      preLoaderRoute: typeof DashboardStudentAiRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/academics': {
      id: '/dashboard/student/academics'
      path: '/academics'
      fullPath: '/dashboard/student/academics'
      preLoaderRoute: typeof DashboardStudentAcademicsRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/parent/reports': {
      id: '/dashboard/parent/reports'
      path: '/reports'
      fullPath: '/dashboard/parent/reports'
      preLoaderRoute: typeof DashboardParentReportsRouteImport
      parentRoute: typeof DashboardParentRoute
    }
    '/dashboard/parent/recommendations': {
      id: '/dashboard/parent/recommendations'
      path: '/recommendations'
      fullPath: '/dashboard/parent/recommendations'
      preLoaderRoute: typeof DashboardParentRecommendationsRouteImport
      parentRoute: typeof DashboardParentRoute
    }
    '/dashboard/parent/mentor-notes': {
      id: '/dashboard/parent/mentor-notes'
      path: '/mentor-notes'
      fullPath: '/dashboard/parent/mentor-notes'
      preLoaderRoute: typeof DashboardParentMentorNotesRouteImport
      parentRoute: typeof DashboardParentRoute
    }
    '/dashboard/parent/growth': {
      id: '/dashboard/parent/growth'
      path: '/growth'
      fullPath: '/dashboard/parent/growth'
      preLoaderRoute: typeof DashboardParentGrowthRouteImport
      parentRoute: typeof DashboardParentRoute
    }
    '/dashboard/parent/communication': {
      id: '/dashboard/parent/communication'
      path: '/communication'
      fullPath: '/dashboard/parent/communication'
      preLoaderRoute: typeof DashboardParentCommunicationRouteImport
      parentRoute: typeof DashboardParentRoute
    }
    '/dashboard/parent/attendance': {
      id: '/dashboard/parent/attendance'
      path: '/attendance'
      fullPath: '/dashboard/parent/attendance'
      preLoaderRoute: typeof DashboardParentAttendanceRouteImport
      parentRoute: typeof DashboardParentRoute
    }
    '/dashboard/mentor/students': {
      id: '/dashboard/mentor/students'
      path: '/students'
      fullPath: '/dashboard/mentor/students'
      preLoaderRoute: typeof DashboardMentorStudentsRouteImport
      parentRoute: typeof DashboardMentorRoute
    }
    '/dashboard/mentor/sessions': {
      id: '/dashboard/mentor/sessions'
      path: '/sessions'
      fullPath: '/dashboard/mentor/sessions'
      preLoaderRoute: typeof DashboardMentorSessionsRouteImport
      parentRoute: typeof DashboardMentorRoute
    }
    '/dashboard/mentor/progress': {
      id: '/dashboard/mentor/progress'
      path: '/progress'
      fullPath: '/dashboard/mentor/progress'
      preLoaderRoute: typeof DashboardMentorProgressRouteImport
      parentRoute: typeof DashboardMentorRoute
    }
    '/dashboard/mentor/plans': {
      id: '/dashboard/mentor/plans'
      path: '/plans'
      fullPath: '/dashboard/mentor/plans'
      preLoaderRoute: typeof DashboardMentorPlansRouteImport
      parentRoute: typeof DashboardMentorRoute
    }
    '/dashboard/mentor/alerts': {
      id: '/dashboard/mentor/alerts'
      path: '/alerts'
      fullPath: '/dashboard/mentor/alerts'
      preLoaderRoute: typeof DashboardMentorAlertsRouteImport
      parentRoute: typeof DashboardMentorRoute
    }
    '/dashboard/admin/teachers': {
      id: '/dashboard/admin/teachers'
      path: '/teachers'
      fullPath: '/dashboard/admin/teachers'
      preLoaderRoute: typeof DashboardAdminTeachersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/students': {
      id: '/dashboard/admin/students'
      path: '/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof DashboardAdminStudentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/reports': {
      id: '/dashboard/admin/reports'
      path: '/reports'
      fullPath: '/dashboard/admin/reports'
      preLoaderRoute: typeof DashboardAdminReportsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/profile': {
      id: '/dashboard/admin/profile'
      path: '/profile'
      fullPath: '/dashboard/admin/profile'
      preLoaderRoute: typeof DashboardAdminProfileRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/mentors': {
      id: '/dashboard/admin/mentors'
      path: '/mentors'
      fullPath: '/dashboard/admin/mentors'
      preLoaderRoute: typeof DashboardAdminMentorsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/membership': {
      id: '/dashboard/admin/membership'
      path: '/membership'
      fullPath: '/dashboard/admin/membership'
      preLoaderRoute: typeof DashboardAdminMembershipRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/cms': {
      id: '/dashboard/admin/cms'
      path: '/cms'
      fullPath: '/dashboard/admin/cms'
      preLoaderRoute: typeof DashboardAdminCmsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/analytics': {
      id: '/dashboard/admin/analytics'
      path: '/analytics'
      fullPath: '/dashboard/admin/analytics'
      preLoaderRoute: typeof DashboardAdminAnalyticsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingAssessmentRoute: typeof MarketingAssessmentRoute
  MarketingCareerRoute: typeof MarketingCareerRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingDemoRoute: typeof MarketingDemoRoute
  MarketingFrameworkRoute: typeof MarketingFrameworkRoute
  MarketingMentoringRoute: typeof MarketingMentoringRoute
  MarketingSlecRoute: typeof MarketingSlecRoute
  MarketingStoriesRoute: typeof MarketingStoriesRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingAssessmentRoute: MarketingAssessmentRoute,
  MarketingCareerRoute: MarketingCareerRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingDemoRoute: MarketingDemoRoute,
  MarketingFrameworkRoute: MarketingFrameworkRoute,
  MarketingMentoringRoute: MarketingMentoringRoute,
  MarketingSlecRoute: MarketingSlecRoute,
  MarketingStoriesRoute: MarketingStoriesRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface DashboardAdminRouteChildren {
  DashboardAdminAnalyticsRoute: typeof DashboardAdminAnalyticsRoute
  DashboardAdminCmsRoute: typeof DashboardAdminCmsRoute
  DashboardAdminMembershipRoute: typeof DashboardAdminMembershipRoute
  DashboardAdminMentorsRoute: typeof DashboardAdminMentorsRoute
  DashboardAdminProfileRoute: typeof DashboardAdminProfileRoute
  DashboardAdminReportsRoute: typeof DashboardAdminReportsRoute
  DashboardAdminStudentsRoute: typeof DashboardAdminStudentsRoute
  DashboardAdminTeachersRoute: typeof DashboardAdminTeachersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAnalyticsRoute: DashboardAdminAnalyticsRoute,
  DashboardAdminCmsRoute: DashboardAdminCmsRoute,
  DashboardAdminMembershipRoute: DashboardAdminMembershipRoute,
  DashboardAdminMentorsRoute: DashboardAdminMentorsRoute,
  DashboardAdminProfileRoute: DashboardAdminProfileRoute,
  DashboardAdminReportsRoute: DashboardAdminReportsRoute,
  DashboardAdminStudentsRoute: DashboardAdminStudentsRoute,
  DashboardAdminTeachersRoute: DashboardAdminTeachersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardMentorRouteChildren {
  DashboardMentorAlertsRoute: typeof DashboardMentorAlertsRoute
  DashboardMentorPlansRoute: typeof DashboardMentorPlansRoute
  DashboardMentorProgressRoute: typeof DashboardMentorProgressRoute
  DashboardMentorSessionsRoute: typeof DashboardMentorSessionsRoute
  DashboardMentorStudentsRoute: typeof DashboardMentorStudentsRoute
  DashboardMentorIndexRoute: typeof DashboardMentorIndexRoute
}

const DashboardMentorRouteChildren: DashboardMentorRouteChildren = {
  DashboardMentorAlertsRoute: DashboardMentorAlertsRoute,
  DashboardMentorPlansRoute: DashboardMentorPlansRoute,
  DashboardMentorProgressRoute: DashboardMentorProgressRoute,
  DashboardMentorSessionsRoute: DashboardMentorSessionsRoute,
  DashboardMentorStudentsRoute: DashboardMentorStudentsRoute,
  DashboardMentorIndexRoute: DashboardMentorIndexRoute,
}

const DashboardMentorRouteWithChildren = DashboardMentorRoute._addFileChildren(
  DashboardMentorRouteChildren,
)

interface DashboardParentRouteChildren {
  DashboardParentAttendanceRoute: typeof DashboardParentAttendanceRoute
  DashboardParentCommunicationRoute: typeof DashboardParentCommunicationRoute
  DashboardParentGrowthRoute: typeof DashboardParentGrowthRoute
  DashboardParentMentorNotesRoute: typeof DashboardParentMentorNotesRoute
  DashboardParentRecommendationsRoute: typeof DashboardParentRecommendationsRoute
  DashboardParentReportsRoute: typeof DashboardParentReportsRoute
  DashboardParentIndexRoute: typeof DashboardParentIndexRoute
}

const DashboardParentRouteChildren: DashboardParentRouteChildren = {
  DashboardParentAttendanceRoute: DashboardParentAttendanceRoute,
  DashboardParentCommunicationRoute: DashboardParentCommunicationRoute,
  DashboardParentGrowthRoute: DashboardParentGrowthRoute,
  DashboardParentMentorNotesRoute: DashboardParentMentorNotesRoute,
  DashboardParentRecommendationsRoute: DashboardParentRecommendationsRoute,
  DashboardParentReportsRoute: DashboardParentReportsRoute,
  DashboardParentIndexRoute: DashboardParentIndexRoute,
}

const DashboardParentRouteWithChildren = DashboardParentRoute._addFileChildren(
  DashboardParentRouteChildren,
)

interface DashboardStudentRouteChildren {
  DashboardStudentAcademicsRoute: typeof DashboardStudentAcademicsRoute
  DashboardStudentAiRoute: typeof DashboardStudentAiRoute
  DashboardStudentAssessmentsRoute: typeof DashboardStudentAssessmentsRoute
  DashboardStudentCareerRoute: typeof DashboardStudentCareerRoute
  DashboardStudentGoalsRoute: typeof DashboardStudentGoalsRoute
  DashboardStudentMentorRoute: typeof DashboardStudentMentorRoute
  DashboardStudentPlannerRoute: typeof DashboardStudentPlannerRoute
  DashboardStudentPortfolioRoute: typeof DashboardStudentPortfolioRoute
  DashboardStudentProfileRoute: typeof DashboardStudentProfileRoute
  DashboardStudentReportsRoute: typeof DashboardStudentReportsRoute
  DashboardStudentSessionsRoute: typeof DashboardStudentSessionsRoute
  DashboardStudentSkillsRoute: typeof DashboardStudentSkillsRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
}

const DashboardStudentRouteChildren: DashboardStudentRouteChildren = {
  DashboardStudentAcademicsRoute: DashboardStudentAcademicsRoute,
  DashboardStudentAiRoute: DashboardStudentAiRoute,
  DashboardStudentAssessmentsRoute: DashboardStudentAssessmentsRoute,
  DashboardStudentCareerRoute: DashboardStudentCareerRoute,
  DashboardStudentGoalsRoute: DashboardStudentGoalsRoute,
  DashboardStudentMentorRoute: DashboardStudentMentorRoute,
  DashboardStudentPlannerRoute: DashboardStudentPlannerRoute,
  DashboardStudentPortfolioRoute: DashboardStudentPortfolioRoute,
  DashboardStudentProfileRoute: DashboardStudentProfileRoute,
  DashboardStudentReportsRoute: DashboardStudentReportsRoute,
  DashboardStudentSessionsRoute: DashboardStudentSessionsRoute,
  DashboardStudentSkillsRoute: DashboardStudentSkillsRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
}

const DashboardStudentRouteWithChildren =
  DashboardStudentRoute._addFileChildren(DashboardStudentRouteChildren)

interface DashboardSuperRouteChildren {
  DashboardSuperActivityRoute: typeof DashboardSuperActivityRoute
  DashboardSuperRevenueRoute: typeof DashboardSuperRevenueRoute
  DashboardSuperSchoolsRoute: typeof DashboardSuperSchoolsRoute
  DashboardSuperSubscriptionsRoute: typeof DashboardSuperSubscriptionsRoute
  DashboardSuperUsersRoute: typeof DashboardSuperUsersRoute
  DashboardSuperIndexRoute: typeof DashboardSuperIndexRoute
}

const DashboardSuperRouteChildren: DashboardSuperRouteChildren = {
  DashboardSuperActivityRoute: DashboardSuperActivityRoute,
  DashboardSuperRevenueRoute: DashboardSuperRevenueRoute,
  DashboardSuperSchoolsRoute: DashboardSuperSchoolsRoute,
  DashboardSuperSubscriptionsRoute: DashboardSuperSubscriptionsRoute,
  DashboardSuperUsersRoute: DashboardSuperUsersRoute,
  DashboardSuperIndexRoute: DashboardSuperIndexRoute,
}

const DashboardSuperRouteWithChildren = DashboardSuperRoute._addFileChildren(
  DashboardSuperRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AssessmentsRoute: AssessmentsRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  MentoringProgramRoute: MentoringProgramRoute,
  RegisterRoute: RegisterRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardMentorRoute: DashboardMentorRouteWithChildren,
  DashboardParentRoute: DashboardParentRouteWithChildren,
  DashboardStudentRoute: DashboardStudentRouteWithChildren,
  DashboardSuperRoute: DashboardSuperRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
