export const NOTIFICATION_REPOSITORY_TOKEN = Symbol('INotificationRepository');

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  PUSH = 'PUSH',
  WEBSOCKET = 'WEBSOCKET',
}

export enum NotificationType {
  ASSESSMENT_PUBLISHED = 'ASSESSMENT_PUBLISHED',
  ASSESSMENT_REMINDER = 'ASSESSMENT_REMINDER',
  ASSIGNMENT_CREATED = 'ASSIGNMENT_CREATED',
  ASSIGNMENT_DUE = 'ASSIGNMENT_DUE',
  ASSIGNMENT_GRADED = 'ASSIGNMENT_GRADED',
  ATTENDANCE_ALERT = 'ATTENDANCE_ALERT',
  LOW_ATTENDANCE_WARNING = 'LOW_ATTENDANCE_WARNING',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',
  LEARNING_DNA_UPDATED = 'LEARNING_DNA_UPDATED',
  VEDHKRIT_INDEX_UPDATED = 'VEDHKRIT_INDEX_UPDATED',
  CAREER_RECOMMENDATION_UPDATED = 'CAREER_RECOMMENDATION_UPDATED',
  GOAL_ACHIEVED = 'GOAL_ACHIEVED',
  CERTIFICATE_ISSUED = 'CERTIFICATE_ISSUED',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  FEE_DUE = 'FEE_DUE',
  SCHOOL_ANNOUNCEMENT = 'SCHOOL_ANNOUNCEMENT',
  ORGANIZATION_ANNOUNCEMENT = 'ORGANIZATION_ANNOUNCEMENT',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum DeliveryStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
  DEAD_LETTER = 'DEAD_LETTER',
}

export enum TargetAudienceRole {
  ALL = 'ALL',
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  PARENT = 'PARENT',
  MENTOR = 'MENTOR',
  ADMIN = 'ADMIN',
}
