export const ATTENDANCE_REPOSITORY_TOKEN = Symbol('IAttendanceRepository');

export enum AttendanceType {
  DAILY = 'DAILY',
  SUBJECT_WISE = 'SUBJECT_WISE',
  LECTURE = 'LECTURE',
  BATCH = 'BATCH',
  CLASS = 'CLASS',
  TEACHER = 'TEACHER',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  HALF_DAY = 'HALF_DAY',
  MEDICAL_LEAVE = 'MEDICAL_LEAVE',
  APPROVED_LEAVE = 'APPROVED_LEAVE',
  HOLIDAY = 'HOLIDAY',
  EXCUSED = 'EXCUSED',
}

export enum AttendanceMode {
  MANUAL = 'MANUAL',
  QR_CODE = 'QR_CODE',
  GEOFENCE = 'GEOFENCE',
  FACE_RECOGNITION = 'FACE_RECOGNITION',
  BIOMETRIC = 'BIOMETRIC',
}

export enum LeaveType {
  STUDENT_LEAVE = 'STUDENT_LEAVE',
  TEACHER_LEAVE = 'TEACHER_LEAVE',
  MEDICAL = 'MEDICAL',
  CASUAL = 'CASUAL',
  SICK = 'SICK',
  SPECIAL = 'SPECIAL',
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum HolidayType {
  NATIONAL = 'NATIONAL',
  SCHOOL = 'SCHOOL',
  ACADEMIC_CALENDAR = 'ACADEMIC_CALENDAR',
  ORGANIZATION = 'ORGANIZATION',
  EXAM = 'EXAM',
}

export enum SessionStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
}
