export const INTEGRATIONS_REPOSITORY_TOKEN = 'INTEGRATIONS_REPOSITORY_TOKEN';

export enum ConnectorCategory {
  EDUCATION = 'EDUCATION',
  COMMUNICATION = 'COMMUNICATION',
  STORAGE = 'STORAGE',
  PAYMENTS = 'PAYMENTS',
  IDENTITY = 'IDENTITY',
}

export enum ConnectorType {
  GOOGLE_CLASSROOM = 'GOOGLE_CLASSROOM',
  MOODLE = 'MOODLE',
  STRIPE = 'STRIPE',
  TWILIO = 'TWILIO',
  S3 = 'S3',
  OAUTH = 'OAUTH',
}

export enum SyncStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
