export const AI_REPOSITORY_TOKEN = 'AI_REPOSITORY_TOKEN';

export enum AIProviderType {
  OPENAI = 'OPENAI',
  GEMINI = 'GEMINI',
  ANTHROPIC = 'ANTHROPIC',
  AZURE_OPENAI = 'AZURE_OPENAI',
}

export enum PromptType {
  STUDY_PLAN = 'STUDY_PLAN',
  LEARNING_INSIGHTS = 'LEARNING_INSIGHTS',
  CAREER_ADVICE = 'CAREER_ADVICE',
  RISK_ANALYSIS = 'RISK_ANALYSIS',
  TEACHER_ASSISTANT = 'TEACHER_ASSISTANT',
  PARENT_SUMMARY = 'PARENT_SUMMARY',
}
