export const ASSIGNMENT_REPOSITORY_TOKEN = Symbol('IAssignmentRepository');

export enum AssignmentCategory {
  HOMEWORK = 'HOMEWORK',
  CLASSWORK = 'CLASSWORK',
  PROJECT = 'PROJECT',
  PRACTICAL = 'PRACTICAL',
  LAB_ASSIGNMENT = 'LAB_ASSIGNMENT',
  GROUP_ASSIGNMENT = 'GROUP_ASSIGNMENT',
  INDIVIDUAL_ASSIGNMENT = 'INDIVIDUAL_ASSIGNMENT',
  CAPSTONE_PROJECT = 'CAPSTONE_PROJECT',
}

export enum AssignmentStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  CLOSED = 'CLOSED',
}

export enum SubmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  GRADED = 'GRADED',
  RETURNED = 'RETURNED',
  REOPENED = 'REOPENED',
  OVERDUE = 'OVERDUE',
}

export enum GradingType {
  MANUAL = 'MANUAL',
  RUBRIC_BASED = 'RUBRIC_BASED',
  AUTO_GRADED = 'AUTO_GRADED',
}
