export const LEARNING_DNA_REPOSITORY_TOKEN = Symbol('ILearningDnaRepository');

export enum LearningStyle {
  VISUAL = 'VISUAL',
  AUDITORY = 'AUDITORY',
  KINESTHETIC = 'KINESTHETIC',
  READING_WRITING = 'READING_WRITING',
}

export enum PreferredLearningMode {
  CONCEPT_VIDEOS = 'CONCEPT_VIDEOS',
  INTERACTIVE_PRACTICE = 'INTERACTIVE_PRACTICE',
  TEXT_DOCUMENTATION = 'TEXT_DOCUMENTATION',
  PEER_DISCUSSION = 'PEER_DISCUSSION',
}

export enum RecommendedActionType {
  REVISION = 'REVISION',
  PRACTICE_QUIZ = 'PRACTICE_QUIZ',
  ADVANCED_LESSON = 'ADVANCED_LESSON',
  CONCEPT_VIDEO = 'CONCEPT_VIDEO',
}
